### ISSUE TITLE
Strange render of widgets

### ISSUE THREAD

**Issue by Lvieira21** [vecnehladny/ubersicht-ios-clock-upnext-weather#4]
Well, at first I had the problem with the icon render, that was an easy fix (added lines of height in calendar and weather "header img").

But I still have a white bar beside the widget, how can I get rid of that?

![Captura de Tela 2020-08-08 às 19 41 53](https://user-images.githubusercontent.com/14310311/89721057-4b0f0080-d9af-11ea-88f7-4118ef73b360.png)

**Comment by twfarley** [comment]
Set overflow-y to auto in weather and calendar.
